### ISSUE TITLE
Introduction to OpenSpending document for pilot partners

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1063]
# Description

A document/template for use when we onboard pilot partners to OpenSpending.

The document should be well structured, introducing pilot partners to:
- the general OpenSpending ecosystem,
- to Fiscal Data Package,
- to the OpenSpending platform, 
- and, provide links to all general purpose resources (the organisation on GitHub, the documentation, the landing package, explorer, packager, viewer, and so on).
- an FAQ section

The document should have a clear, simple tutorial for "getting started with OpenSpending", which provides text and images to describe:
- Preparing data
- Packaging data
- Loading data
- Exploring data
- Interacting with data
- Exporting data

Note that this tutorial aspect aligns with my longstanding issues for such work in the docs [here](https://github.com/openspending/openspending/issues/896) and [here](https://github.com/openspending/openspending/issues/899), and this work should be integrated with those pages so as to be able to close those issues too.

Along with the above defined general sections to introduce the pilot partner to the ecosystem, and to guide the pilot partner through fist use of OpenSpending, There should be a section for pilot-specific information. This would be blank, as it depends on each pilot case, but having a basic, useful structure in place will allow us to proceed with all future pilot partners in a consistent manner. Likely sub-sections for this section would be:
- Overview: the outline of the pilot, included the goals
- Meetings: a description of the meeting schedule between the core team and the pilot partners
- Scope: a specific list of the work to be done for the pilot. This is very specific to each pilot.
- Timeline: a list of the timeline for the pilot work.
# Tasks
- [x] Create a new "Pilot Template" section of the docs, for the pilot-specific template, implementing it as required
- [x] Implement the "Contributors" and "Users" sections of the docs, which are placeholders for tutorials that target these user groups
- [x] Write out the first draft of all and share with @akariv and @pwalsh

**Comment by pwalsh** [comment]
@annafralberts this can also be reused on OBEU directly, so when we have a draft it would be great to have your input.

**Comment by VictoriaVlad** [comment]
@akariv, @pwalsh, please see the first draft here https://goo.gl/iiAew9

**Comment by pwalsh** [comment]
Hi @VictoriaVlad 

Great start! 

I made several comments in the doc, and I added @annafralberts and Diana so they can also comment and edit the doc. Anna's comments are important as in OpenBudgets we also need to pilot OpenSpending and the more custom OpenBudgets tools, so all this material will be a common base for that too.

For our immediate pilot needs: please address my comments, and then we'll take it up again Aug 29 when I return.

**Comment by pwalsh** [comment]
@VictoriaVlad what is the latest status here?

( cc @DianaMPG  )

**Comment by VictoriaVlad** [comment]
Hi @pwalsh,

I've addressed the comments in the document, including, but not limited to:
1.  Editing the formulation of the aim of OpenSpending
2. In regards to tutorials for docs.openspending.org, I've added them as Markdown to the docs themselves, and then reduced the text to a short intro to each tutorial in the doc (I forked the OS docs repo, and added the steps and images for all walkthroughs. I created a pull request to original repository)
3. Added the scope from Mexico document
4. Added some more FAQs and need clarification for some questions.

The document is ready for final review.

cc @DianaMPG

**Comment by DianaMPG** [comment]
Hi @pwalsh @akariv 

Please review overall structure of the doc.

thanks
Diana

**Comment by DianaMPG** [comment]
@pwalsh @akariv 

I have now edited the content of What is OpenSpending to OpenSpending and governments, so this first part is ready for review.

Will now work on the Scope ...

**Comment by DianaMPG** [comment]
@pwalsh @VictoriaVlad @akariv 
Timeline for reviewing Intro to OS for PPPs:
- OS Team: reviewing and final edits done by Friday 6pm CET 
- Sending it out for review request to GIFT (Juan Pablo and Tania): Monday 5th of Sept, asking for their feedback by Wednesday, 7th of Sept.
- OS team (Diana and Victoria): editing Gift`s comments by the 9th of Sept. Final OS team review on
9th of Sept
- Sending it out to the WB team for review: 9th of Sept, evening
