### ISSUE TITLE
Consolidate notes on community: status and road forward

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1073]
# Description

We need to put an explicit plan in place for working with the existing fiscal data community, helping to give it a common home, and place the new work around OS in it.

# Tasks

- [x] Get all notes from previous meetings into a shareable format
- [x] Organise a couple of calls to sync with @annafralberts especially as not to duplicate work that she and the OKDE team have already done (lots of work done there as part of the OBEU project in terms of mapping fiscal community)
- [x] Work on document that identifies all existing and potential communication channels, including those like conferences
- [x] Work towards a document that identifies current status and future direction. This will help inform concrete steps we take over the next 6 months or so

**Comment by pwalsh** [comment]
cc @annafralberts

**Comment by VictoriaVlad** [comment]
document drafted here: https://docs.google.com/document/d/11SKNfCh9slWm5c_cbF8sj-xoKL4V9FHDbdigNfj46HU/edit#heading=h.xcqffvjhrdoo. Diana, Sierra and Mor had an initial look at the doc.
