### ISSUE TITLE
Add persistent, immutable identifiers for facts and dimensions

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1186]
# Description

After engaging https://github.com/open-contracting/standard/issues/378#issuecomment-266992145 and reflecting on some earlier work I did [here](https://github.com/pwalsh/openbudgets), I think we should make a commitment to the wider ecosystem of persistent, immutable identifiers for fiscal facts and dimensions.

We know we can't expect source data to provide unique identifiers for fiscal data. I do not see us getting close to this anytime soon. However, an express goal of the new OpenSpending platform is to centralise a large amount of the world's fiscal data for deep usage and analysis. 

As long as we have clear [data provenance](https://github.com/frictionlessdata/datapackage-pipelines) for large amounts of that data that we are actively ingesting, then we can offer unique identifiers for the rest of the fiscal data ecosystem.

As I have [noted here](https://github.com/open-contracting/standard/issues/378#issuecomment-267000031), creating unique identifiers for lines of fiscal data that do not declare their own unique identifiers is a very difficult task. I'm quite sure we'll not have a 100% or even 90% success rate with whatever algorithms and conventions we employ to do so (note that it is not a one time assignment - we need to try to ensure immutable persistence across data updates etc.). However, we'll get it right in many, many cases and that is probably worth more to fiscal transparency as a whole, than the % of mistakes the platform will generate. 

@akariv what do you think, and what challenges do we have?

cc @timgdavies @pudo @annafralberts @rufuspollock thoughts from any of you are greatly appreciated

# Tasks

- [ ] Estimate what it requires to add additional endpoints for each single fact and each unique dimension instance, across the whole database
- [ ] Estimate possible approaches to using unique identifiers from the source when they exist, and otherwise generating custom unique identifiers that are persistent and immutable as far as OpenSpending is concerned
- [ ] Related, with the [pipelines framework](https://github.com/frictionlessdata/datapackage-pipelines) we have opportunities for recording data provenance for fiscal data that have not been possible on similar platforms (including the old OpenSpending) to date. We should think about how we expose some provenance facts via the API as well

**Comment by timgdavies** [comment]
Thanks @pwalsh.

The mix of using incoming identifiers, and falling back on auto-generated IDs makes really good sense. I like the way it provides an incentive for publishers to provide IDs (and can demonstrate the benefits), but also handles when they do not. 

One of the things to think about might be how to handle those failure cases where a former identifier no longer points to a data item. The main use-cases I have mind for persistent IDs & then URIs for budget lines are:

* **Social sharing** - people linking, in blog posts, social media etc, to individual transactions (a surprisingly common, and interesting use case in terms of empowering people with data);
* **Data linking** - when one dataset (e.g. Open Contracting) provides a link out to external transactions which a system might follow in order to find / scrape etc. additional context about transactions;

In the first case, a friendly 'not found' message, perhaps with box to help to search for the data, might do well. In the second, I can see two scenarios:

(1) Where there was originally no identifier in the source so IDs were generated, but the publisher is now providing their own IDs. In some cases it might be possible to redirect to the new ID, or maintain both the old and new IDs?
(2) Where there are no IDs and changes to the dataset breaks the persistent IDs. In this case, knowing what **used to be** a valid ID could be useful, but I'm not sure how much the OS architecture stores history of datasets - and guess this might be a much more complex thing to handle?

With the data linking cases - I'm aware these **are** tricky, and so I'm not suggesting OS should try and implement all the things needed to handle them. Another approach may be to just give users viewing a persistent URI some indication of how persistent it is, and whether they would be advised or not to incorporate it in any data linkage. 

Hope this helps.

**Comment by pwalsh** [comment]
hey @timgdavies 

- For case 1: we `MUST` implement a redirect system, and possibly have the old identifier as a property of the new API resource which is identified by the new identifier
- For case 2: in some cases it will be impossible (for the platform) to know it "broke" an identifier for a fact in the world. Note sure how we will handle that. I think there are subclasses to this case too

**Comment by jpmckinney** [comment]
This sounds good.

With respect to whether OpenSpending mints its own new identifiers for facts and dimensions if these aren't in the source data or in the OFDP file, I suppose that's up to OpenSpending.

Is there a comparable issue on https://github.com/openspending/fiscal-data-package/issues about identifiers? I'm more interested in getting this right in OFDP than in OpenSpending.

**Comment by pwalsh** [comment]
@jpmckinney I started one here https://github.com/frictionlessdata/specs/issues/524

**Comment by pwalsh** [comment]
@akariv can you do a task list / requirements scope for this please.

**Comment by akariv** [comment]
Based on our conversations with the OCP folks, I propose we follow their lead and decide that a _unique identifier_ for a fact is simply the list of values of the fields comprising the dataset's primary key. 
For valid datasets, this should be enough to locate (at most) one record in the dataset.
This method is also quite resilient to modifications in the data itself - implicitly supporting new or modified rows or missing columns.

In terms of representation, we could have many equivalent representations. For example, all of these represent the same unique identifier for a row in a given dataset:
```json
{
   "year": 2017,
   "project": "invisible jet",
   "supplier": "ACME corp."
}
```
or
```yaml
year: 2017
project: invisible jet
supplier: ACME corp.
```
or
```
https://openspending.org/api/3/facts?dataset=defence_projects&year=2017&project="invisible jet"&supplier="ACME corp."
```

**Comment by pwalsh** [comment]
@akariv 

While the three fields above are enough for uniqueness within a Fiscal Data Package, I think for unique and persistent IDs on OS we might need more?

How about:

```
unique = (('user', 'os_user'), ('dataset', 'defence_project'), ('year', 2017), ('project', 'invisible jet'), ('supplier', 'ACME corp.'))
id = hash(unique) # can compute this on load and save it somewhere
```

And then a simpler URL like:

```
https://openspending.org/api/3/facts/2643224853786480527/
```

WDYT?

**Comment by akariv** [comment]
@pwalsh the main problem I see with this approach is that you would need to save these hashes along with the data, which is something that is avoided when not hashing.
Another thing we lose is readability in urls.
Finally hashing tends to be very brittle and would need exact coordination on the hashing algorithm, whitespace, character encoding, data types etc. etc.

**Comment by jpmckinney** [comment]
Readability is not a requirement for identification, e.g. numeric identifiers are very commonly used for identification. You can always use redirects if you really want a readable URL in the end.

A concatenation of values as an identifier seems fine to me. I just want to be sure that the proposed concatenation works for budgets (not just expenditures), e.g. the supplier is typically not known in the budget.

**Comment by pwalsh** [comment]
@akariv you've got the email, but for public record in case you need to review, here is how Mexico are currently linking across data standards (FDP <> OCDS):

From Lorena:

> You can find a ocds release with the Budget Breakdown attached in this mail. You can also find further information about how the extension was developed in the Github discussions https://github.com/open-contracting/standard/issues/483. We connect OFDP and OCDS by two ways:

> - By using pivot entries: Both OCDS and OFDP have pivot entries that allow going from one standard to another. For example: The Budget Breakdown id corresponds to a budget program identifier, which can be consulted using the OS Viewer or the API. For example, the release with ocid “ocds-07smqs-1285369” has the Budget Breakdown id “04M001”. Since the 2 first digits correspond to “Ramo”, while the third to “Modalidad” and the last three to “Programa Presupuestario”  you can use the API to find it in OFDP (http://next.openspending.org/api/3/cubes/6018ab87076187018fc29c94a68a3cd2:presupuesto-mexico-2008-2018/facts/?cut=date_2.CICLO:%222017%22|administrative_classification_2.ID_RAMO:%224%22|activity_ID_MODALIDAD.ID_MODALIDAD:%22M%22|activity_ID_PP.ID_PP:%221%22|pagesize=10). The same information can be searched in the viewer.

**Comment by akariv** [comment]
So @pwalsh from what I understand, Mexico are using a customised concatenation of ids from their budget files to create the unique id. This is inline with my suggestions from above.
I still think that the actual representation should be determined by the implementation and not standardise it. That is, the spec should explain how unique ids could be combined to create a unique row id, but the exact way of representing and combining the values should remain implementation dependent.
