### ISSUE TITLE
Update existing Datastore to Fiscal Data Package v1

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1256]
All existing datasets on OpenSpending updated to the new specification and development.

**Comment by pwalsh** [comment]
# Description

When we release v1, we have the opportunity to upgrade all FDPs on the OS datastore to the new spec. We should do so.

# Tasks

- [ ] Write a script to update all packages in the OpenSpending Datastore to FDP v1
- [ ] Test the script (write tests, and manual sort checks)
- [ ] Update the datastore

**Comment by akariv** [comment]
I'm not sure this is a good idea - this change might affect the API names and might break things for users in ways we can't foresee.
I think FDPv1 should be applied to all new datasets only.

**Comment by pwalsh** [comment]
@akariv that is fine, I just want to then be sure that there is no unexpected breakage, that we know about any possible limitations on old datasets in terms of functionality and so on.

cc @sandervdwaal

**Comment by sandervdwaal** [comment]
Discussed with @brew - we are closing this to prevent unintended side effects.
Editing a fiscal data package will upgrade to v1.0 when saved.
Open question about versioning of data packages will be addressed elsewhere.
