### ISSUE TITLE
Design enhancements for the Packager

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1276]
# Description

We have been working on this on and off for several months, with lots of existing mocks from @smth 

We have a few remaining issues to close off on in terms of design, and then we can finalise the implementation.

All the existing work is at https://github.com/smth/os-mockups

# Tasks

- [ ] Review existing designs
- [ ] Add additional enhancements (TBD)
- [ ] Publish final HTML mocks for implementation by the dev team

**Comment by pwalsh** [comment]
Most recent comment from @smth 

> I just took a little time to remind myself where I got to last time I was looking at this. I think it's worth sharing to get some feedback. I'd been working on an idea in which the first step of "describing" the data would be to go through each card in turn, and assign a "data type". This process would reorder and colour code the cards as you go. Once done, you are then free to edit titles and add descriptions, much as before. You can also revisit the data type interface for any card. Here's a pretty much static, and slightly rough mockup http://p.smth.uk/os-mockup-packager/packager/map-data/ It shows one assigned card (in the background) and one ready to be assigned. Hopefully it gives an idea of how it would work.

**Comment by pwalsh** [comment]
@smth note some issues encountered on implementation, by @kravets-levko have been noted here: https://github.com/smth/os-mockups/issues/1#issue-203981662

Please address as part of finishing the design.

**Comment by pwalsh** [comment]
As best as we can tell, this is done, and the blocker is on implementation, plus any design enhancements that will come out of implementation. Closing.
