### ISSUE TITLE
Design implementation for the Packager

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1277]
# Description

We have been working on the Packager redesign for some months, between other things, as noted in https://github.com/openspending/openspending/issues/1276

When https://github.com/openspending/openspending/issues/1276 is finished, we need to finish this implementation and ship it.

# Tasks

- [ ] Get all work in progress from when @kravets-levko was working on this
- [ ] Assess remaining work based on final https://github.com/openspending/openspending/issues/1276
- [ ] Verify handling of constants
- [ ] Ship it

**Comment by pwalsh** [comment]
@akariv assigning to you for now just because you are going to get the WIP from @kravets-levko

**Comment by pwalsh** [comment]
I'm closing https://github.com/openspending/openspending/issues/1130 and adding it to this. @akariv indicates he needs to make a change to OS Types for this too.

**Comment by pwalsh** [comment]
@akariv 

No one else has any idea where this is at, and if or when @kravets-levko has any code he can push for others to work on.

Can you please update the exact status, including on checking in with Levko, so others can pick this up in the future if needed.

I'm moving the work to the backlog for now.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (~2 years) as part of #1478. Label `prioritized` was removed a long time ago. Please feel free to re-open if this is still relevant.
