### ISSUE TITLE
[WIP] Requirements for v1 of Fiscal Data Package

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1312]
# Description

(I'm working on this issue over a few days. When it is complete, the "[WIP]" prefix will be removed from the title.)

# Tasks

## Content

- [ ] Remove ambiguity. Some examples I remember: 
  - [ ] relations (FKs)
  - [ ] usage of tag to denote this is budget or spending data
  - [ ] fiscal year and budget phase etc - various properties that are declared as "meta data" but definitely should be dimensions
- [ ] Agree on all properties for budget data, and elevate OpenSpending's related "data types" to more explicit properties of the spec
- [ ] Agree on all properties for spending data, and elevate OpenSpending's related "data types" to more explicit properties of the spec
- [ ] On each of above, review DATA Act, and review the OBEU Data Model ( @pwalsh knows it pretty well but, as our data types work in OS really does start to map to OBEU model explicitly, and because the team there did lots of research, it is worth another close review )
- [ ] Explore ways to make budget phase locale-aware. Flexible yet not complex.
- [ ] Talk about how and why we support multiple measures, and have some good, real-world examples
- [ ] Perhaps have an explicit section that explains, in very clear terms, the differences between the FDP approach and a more "formal/prescriptive" standard. This is a way to talk about our goals around reduced friction and progressive enhancement of data
- [ ] Specify a way for a model to be built from a file without a modelling step, using naming conventions. We have modelling so as to *not* force publishers to change files just to publish to a standard, but it would also be good if the naming convention of the columns could be used, for savvy publishers and/or developers, to build the model automatically
- [ ] Add [transaction IDs](https://github.com/open-contracting/standard/issues/378#issuecomment-266992145) (also ref. [this](https://github.com/openspending/openspending/issues/1186) as we want to build this out, on top of FDP v1 changes)

## Structure

-  [ ] The addition of explicit Data Types in the OS codebase uses strings with `:` as the property accessor, as a flat representation of a nested hierarchy of data types. These data type strings are shipped as annotations on the Table Schema, grouping properties into concepts, and are then used in code that loads FDPs. [Example](https://github.com/openspending/os-types/blob/master/src/os-types.json#L2) [Example](https://github.com/openspending/os-types/blob/master/src/os-types.json#L108). Do we want to formalise this, or, use the `model`?
- [ ] Extract the model/cube work from here, formalise it as a [general FD spec](https://github.com/frictionlessdata/specs/issues/238), and in return ensure that FDP follows that general spec (relates to above point, i.e: representing concepts as strings, or as nested JSON objects on the `model` property)

**Comment by pwalsh** [comment]
cc @akariv @rufuspollock @vitorbaptista @DianaMPG

**Comment by pwalsh** [comment]
I'm now thinking that we can use the profiles concept in Data Packages v1 for different types of fiscal data.

This could be better than trying to hard code "budget" and "spending" as fiscal data types in the default FDP, as we've found that users often do not know the difference anyway.

The basic gist of what I am thinking is:

- FDP has all the data types we need (as above). `fiscal-data-package` is a profile with a minimum Date and Amount requirement, as currently.
- `fiscal-data-package-budget`
- `fiscal-data-package-spending` (or, `-transaction`)
- `fiscal-data-package-contracting`: An implementation of the [Open Contracting Standard](http://standard.open-contracting.org/latest/en/) as Fiscal Data Package.
  - This is quite appealing as writing a small converter from OCS to this would open up not only all the Frictionless Data tooling to users of the Open Contracting Standard, but also the visualisation libraries and APIs of OpenSpending. ( cc @jpmckinney @timgdavies )

Each of these "sub" profiles would have a more explicit list of concepts. UIs and APIs can also provide options for users to explicitly model one of these profiles. Additionally, if a default `fiscal-data-package` is added to a system like OpenSpending, and it has the required concepts, for, example, the Open Contracting profile, it can be "automatically" upgraded.

**Comment by timgdavies** [comment]
@pwalsh Can you say a bit more what you mean by 'An implementation of the Open Contracting Standard as Fiscal Data Package' 

Are you talking about extracting the budget and transaction elements of OCDS data as budget or spend FDP? Or trying to extract more or the contracting process data as well and re-model in FDP?

**Comment by pwalsh** [comment]
Hey @timgdavies 

> Are you talking about extracting the budget and transaction elements of OCDS data as budget or spend FDP? Or trying to extract more or the contracting process data as well and re-model in FDP?

I'm not sure yet, but one of the two. I'll have to work with more data to understand what makes most sense / generates most value.

**Comment by jpmckinney** [comment]
@pwalsh OCDS has hundreds of fields (many of which are prose). I'm not sure what the purpose of transforming all that would be, considering OpenSpending's primary value is with respect to numeric data.

**Comment by pwalsh** [comment]
> @pwalsh OCDS has hundreds of fields (many of which are prose). I'm not sure what the purpose of transforming all that would be, considering OpenSpending's primary value is with respect to numeric data.

Yes, it is unlikely we would transform all that. At the same time, there is a clear subset that may be useful for exploration along numeric measures, hence the exploration of this direction.

**Comment by rufuspollock** [comment]
@pwalsh i think this all makes a lot of sense. I esp like the division into subprofiles rather than one big fat profile and i think incorporating something to support the (numeric) portion of contracts is very useful as it comes up very frequently in fiscal data stuff.

**Comment by pwalsh** [comment]
I've had a session today with @akariv on this. We will take the following next steps:

1. From now to Sept. 18th, Adam will work on a draft document that outlines his vision for how we take the work done in "OS Types", make it a core part of the spec, and thereby remove pretty much all ambiguity.
2. I'll do research on DATA Act and some things @akariv and I discussed around schema.org 
3. We'll then use this material to iterate on a draft. I'll then do that iteration, getting things into a form that makes sense with our specs, noting things that are unresolved or simply not addressed, and then bring in @rufuspollock for discussion and review, ideally by Monday 24th September.

**Comment by rufuspollock** [comment]
@pwalsh acknowledged and sounds good.

**Comment by pwalsh** [comment]
I started breaking this down into issues here https://github.com/frictionlessdata/specs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Fiscal+Data+Package%22
