### ISSUE TITLE
Public feedback stage for v1 of Fiscal Data Package

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1313]
# Description

We plan to have a reasonable draft of Fiscal Data Package v1 by the beginning of October. At that stage, we want to share the draft widely for comments.

There will be a limited time for comments. I suggest a 6 week window from publication of the draft.

# Tasks

- [ ] Have clear path for commenting on the spec
- [ ] Announce via a blogpost and social media that a draft of v1 is published for comments
- [ ] Announce to GIFT Stewards that a draft of v1 is published for comments
- [ ] Announce to Open Contracting team that a draft of v1 is published for comments
- [ ] Announce to OKDE and OKGR (our partners in OpenSpending) that a draft of v1 is published for comments

**Comment by pwalsh** [comment]
cc @DianaMPG @akariv @rufuspollock @vitorbaptista

**Comment by timgdavies** [comment]
In the recent OCDS upgrade, we found combining an open review process, with a semi-structured set of invited peer reviews really improved the coverage of feedback we got. 

We used a spreadsheet template for people to comment issue by issue / on key areas of the spec. It was a bit of an overhead to create, but useful to get directed input, rather than ad-hoc coverage of issues, or very high-level comments that are tricky to process.

**Comment by rufuspollock** [comment]
> In the recent OCDS upgrade, we found combining an open review process, with a semi-structured set of invited peer reviews really improved the coverage of feedback we got.

Thanks Tim, really useful suggestions 👍 🍕

**Comment by DianaMPG** [comment]
@timgdavies may I ask who the peer reviewers were in the recent OCDS upgrade? where they part of the OGP Fiscal Transparency working group?

**Comment by timgdavies** [comment]
@DianaMPG You can find [a list of the peer reviewers here](http://standard.open-contracting.org/latest/en/support/credits/#version-1-1-0)

We tried to invite a set of people representing a broad range of groups, and then also put the peer-review call out through our main channels, so people could volunteer as well (to avoid a closed 'invite-only' process)

**Comment by DianaMPG** [comment]
Thank you @timgdavies !

**Comment by pwalsh** [comment]
part of this (the specific contribution model) will be [addressed here](https://github.com/frictionlessdata/specs/issues/522). This issue remains relevant for the OS project team to work on general outreach around the work to solicit commentary and contribution.

**Comment by pwalsh** [comment]
Closing this now, and team will start a new process for comments on RC1 after announcement.
