### ISSUE TITLE
OpenSpending CLI and Python Client

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1326]
# Description

The OpenSpending Client, currently called [Gobble](https://github.com/openspending/gobble), needs some ❤️ .

# Tasks

- [ ] Rename from `gobble` to `os-client` to be consistent with other OS components
- [ ] Add progress bars to CLI for upload. See original notes [here](https://github.com/openspending/openspending/issues/1104) and my [comment here](https://github.com/openspending/openspending/issues/1104#issuecomment-250150476)
- [ ] Update README to reflect API, and update the [OpenSpending documentation](https://github.com/openspending/docs)
- [ ] Review for any obvious code refactoring. The library is not in a great state
- [ ] Review for, and implement, essential code coverage
- [ ] Check and fix [this bug](https://github.com/openspending/openspending/issues/1153) related to package.json (???)
- [ ] Check and fix these [user module token bugs](https://github.com/openspending/openspending/issues/1103) ( @akariv do these bugs still exist? )

Brook's edit:

- [ ] Upgrade goodtables > 1.0.0
- [x] Remove python support for all version except 3.6
- [x] Remove py2.x futures cruft

**Comment by pwalsh** [comment]
@brew is this task done now?

**Comment by brew** [comment]
No. I completed some tasks as part of other work, but the bulk of it remains.

**Comment by rufuspollock** [comment]
@sglavoie i think we also close this as wontfix. It will be obsolete anyway once on datahub.

**Comment by sglavoie** [comment]
**WONTFIX**: Closing old issue without recent activity as part of #1478. Please feel free to re-open if this is still relevant.
