### ISSUE TITLE
Easily installable OpenSpending

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1333]
# Description

We have been aware of many requests, from governments, to make the new OpenSpending more easily installable on their own infrastructure. We need to scope out this work. We can assume the infrastructure has docker (as the only requirement, rather then, say, a specific Python version, or whatever).

# Tasks

- [ ] What needs to be done to install OpenSpending, versioned, with ease, on any server infrastructure. Assuming this mostly means (i) very clear and simple documentation on all the env vars that need to be set, (ii), alternative to the S3 file store, (iii) Check and enhance our docker deployment setup, and (iv) a suite of integration tests for sanity.
  - [ ] Write a small spec
  - [ ] Provide a high-level estimate
- [ ] What effort would be required to add a layer to OpenSpending which, when installed, send a copy of all published data to the centralised public database?
  - [ ] Write a small spec
  - [ ] Provide a high-level estimate

**Comment by pwalsh** [comment]
@akariv and @vitorbaptista can you please look at this over the coming week, coordinating amongst yourselves. We need input from both of you on this.

@brew please be in sync with them both too.

**Comment by pwalsh** [comment]
@vitorbaptista can you update here with your findings.

**Comment by pwalsh** [comment]
@vitorbaptista did this https://hackmd.io/MwEwTMYAwgRgtAQwKZWPALMsAOePEwA2fAdiIIE4BGSgVgDMjYg=

cc @brew

**Comment by pwalsh** [comment]
reassigned to @brew now we go the spec/overview

**Comment by pwalsh** [comment]
@brew have you addressed all the points in the doc that @vitorbaptista did to scope this? I'm particularly thinking of the S3 replacement for on-premises.

**Comment by brew** [comment]
We provide an S3 alternative for development ([fakeS3](https://github.com/jubos/fake-s3/)), as a convenience, along with other backing services, like postgres etc, which we would expect to be specified as external resources for a production deployment. 

I don't think we should explicitly provide the S3 alternative for production deployments. We don't use it ourselves, and can't provide informed support for its use. I can improve documentation around the use of backing services though, and be more explicit that an S3-compatible service is required, and point out [Minio's Docker support](https://docs.minio.io/docs/minio-docker-quickstart-guide) as a self-hosted alternative.

**Comment by brew** [comment]
Looked a little further to see what would be required to support Minio. Basically we'd need to upgrade boto to boto3 in os-conductor, and migrate the boto methods we use to generate urls. I'll add an issue.

**Comment by pwalsh** [comment]
@brew can this be closed now?
