### ISSUE TITLE
Improve automated data harvesting in os-data-importers

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1381]
Government/Institution users need to be able to define a list of resources and processing steps to output a datapackage to OpenSpending, without having to manually create or edit using os-packager. We have a prototype datapackage-pipeline suite running for Mexico ([os-data-importers](https://github.com/openspending/os-data-importers)). This helps keep OpenSpending data up to date. os-data-importers should be updated to enable it to scale for multiple pipeline users, and improve feedback to pipeline users.

This is a general purpose issue to keep track of the specific work issues:

- [x] separate fiscal.source-spec.yaml configuration files from app code and deployment (#1382) 
- [ ] improve the datapackage-pipelines dashboard to better indicate pipeline status (#1383)
- [ ] document how to create source-specs and best practise (#1384)

**Comment by brew** [comment]
Captured in issues above.
