### ISSUE TITLE
Get list of datasets we will migrate

### ISSUE THREAD

**Issue by sglavoie** [openspending/openspending#1482]
* When migrating to the new OpenSpending setup, I want to only keep those datasets that are "real" and "important" (and discard all the test/random datasets) so that we reduce work and have a cleaner future setup.
* When I select what datasets to migrate (keep), I want criteria to use so that I can (partially) automate the selection process.

## Acceptance

* [X] Selection criteria (metrics) are defined to quickly filter out most of the tables in the database that we can safely discard. **DONE**.

## Tasks

* [x] Evaluate proposed metrics, then approve or reject them. **DONE**.
* [x] Come up with additional/better metrics to dispose of data that won't be useful. **DONE**: Listed below in **Analysis** section.
* [x] Determine ownership of tables as this will help in knowing what's being used by whom. (Part of Epic https://github.com/openspending/openspending/issues/1480). **DONE**.

## Analysis

Some metrics I think could be used or tweaked:

* Any table matching the patterns `test`, `fdptest` or `teste` anywhere in the table name correspond to test data. This is highlighted by simply checking for the pattern `test`.
* Tables matching the regular expression `_v\d` (i.e., `_v1`, `_v2`, etc.) are not useful.
* Tables where the column `Row Count` matches the same number in the column `seq_tup_read` on the same row mean that data was inserted and never accessed again (in other words, dumped there and never actually used).
* Tables with 10 or less rows are too small to contain anything useful, especially if they are not being accessed.
* All empty tables are discarded.
* Any table with `idx_scan = 0` means it was never used. Some tables are duplicates and only one of them may be returning results to clients, so the others with zero read access can be discarded, especially if they are of the same size or lower than the table being actively used.
* Because `idx_scan` tells us about how many times a given table was used, we can probably ascertain the relative importance of tables based on how much they are accessed. As a quick guide, 319 tables have been accessed more than 100,000 times out of 8,233 tables, 1,501 tables have been accessed at least once up to 1,000 times and 5,914 tables have not been accessed at all.
* Filtering larger tables based on the uniqueness of row count and/or size in bytes may also prove useful: it's very unlikely that two huge tables will store the exact same number of bytes, so we can eliminate duplicates in this way.

If we have a list of clients/governments that we know are using OpenSpending (by knowing the ownership of each table), it could also help in filtering out anything that doesn't belong to that list.

### Technique for applying the metrics

In [the spreadsheet](https://docs.google.com/spreadsheets/d/1Cno0jUkfl8ozf0qjaNhuCmJEmMaL2U65sNONqVTEEnM/edit), column `B` contains filters to output either `yes`/`no` in the following way to answer the question "should we keep it?":

```
=IFNA(
IFS(
REGEXMATCH(A:A,"test"), "no",
REGEXMATCH(A:A, "_v\d"), "no",
EQ(C:C,G:G), "no",
C:C<11, "no",
D:D=0, "no",
EQ(H:H,0), "no",
LT(G:G,10000), "no",
LT(H:H, 100), "no"
), "yes")
```

To quickly do this, the formula was entered in the cell `B2`. Then, `B2` was selected, `Shift` was pressed and maintained, scrolling to the last cell in column `B`, clicking on the last cell will select the whole column starting from `B2`. Then, typing `Ctrl+Enter` (or `Cmd+Enter` on Mac) will duplicate the content of `B2` into all the remaining selected cells.

~~So far, I have used conditional formatting based on colors because we can filter by colors in Google Sheets: if the tables to discard have color, then selecting `Filter by Color > Fill Color > White` will show only the tables we are interested in keeping.~~

----
/cc @rufuspollock

**Comment by sglavoie** [comment]
**Done**:
* Issue moved and updated.

**To Do**:
* Convert the existing conditional formatting rules to output text into a new column instead of using colors.

----

Thank you :slightly_smiling_face:.

**Comment by sglavoie** [comment]
@rufuspollock:

*  Filters now output `yes`/`no` in column `B` of [the spreadsheet](https://docs.google.com/spreadsheets/d/1Cno0jUkfl8ozf0qjaNhuCmJEmMaL2U65sNONqVTEEnM/edit) instead of using colors.
* Ownership info is not accessible, I will clear this up in a few minutes with Victor who offered to help and then with Adam if I get blocked because of a credential issue. Until this info is available, I think it makes sense to leave the spreadsheet alone as further filtering will not be effective.

**Comment by sglavoie** [comment]
* Victor helped me get the metadata from Elasticsearch and all of it is now part of the spreadsheet.
* New filters can now be created to remove duplicates where no ownership information exists and where the table name is practically identical except for the fact that it ends with `_X`, where `X` can be any digit. More on this early next week!

**Comment by rufuspollock** [comment]
@sglavoie can you add to the README in https://github.com/openspending/audit-for-migration-2020 a **succinct** explanation of your filter approach and its logic / motivation.

**Comment by sglavoie** [comment]
Yes, I will do that and update you here once it's done. :+1:

**Comment by sglavoie** [comment]
**FIXED**: All tasks were done and a succinct explanation of the filter approach was added to https://github.com/openspending/audit-for-migration-2020.
