### ISSUE TITLE
[trial migration] Move GIFT datasets to github.com/gift-data

### ISSUE THREAD

**Issue by sglavoie** [openspending/openspending#1486]
# Trial migration of GIFT datasets to GitHub

**Job story**: When I migrate data from an S3 bucket (in this case, GIFT datasets), I want to be able to follow an automated process to retrieve the data and re-upload it to Google Cloud Storage while storing the metadata on GitHub so I can safely back up all the data and remove the dependency from the old storage location (S3).

## Acceptance criteria

* [x] https://github.com/gift-data contains all the GIFT datasets metadata.
* [x] All the actual data for GIFT is stored in Google Cloud Storage from this Git-LFS setup.
* [x] There exists an automated – and documented – process to perform this kind of migration.

## Tasks

* [x] Boot github org for GIFT **DONE: github.com/gift-data**
* [x] Spec out layout/approach
* [x] Implement migration
  * [x] Creating a bucket in google storage gift-data
  * [x] Setting up a giftless server
    * [x] Test it manually with a repo – **DONE**: The [gift-data/presupuesto-de-uruguay](https://github.com/gift-data/presupuesto-de-uruguay) repo was set up manually.
  * [x] scripting in python/js migration from s3 to this setup – **DONE**: The script can be found in the [openspending/audit-for-migration-2020](https://github.com/openspending/audit-for-migration-2020/tree/master/s3_to_google_cloud_storage).
* [x] Migrate GIFT datasets
  * [x] Migrate all GIFT datasets shown on this page: http://www.fiscaltransparency.net/ofdp/
  * [x] Create a repo on `github.com/gift-data/{name-of-dataset}` – **DONE**: All created here → https://github.com/gift-data
  * [x] Configure git repo with giftless as git-lfs server – **DONE**: The process was fully described in the [openspending/audit-for-migration-2020](https://github.com/openspending/audit-for-migration-2020/blob/master/s3_to_google_cloud_storage/README.md).
  * [x] Copy over `datapackage.json` from s3 to repo – **DONE**: All GIFT repos have their own `datapackage.json`.
  * [x] Copy over files – **DONE**: All files were backed up on Google Cloud Storage with Giftless and repos are all set up with Git-LFS.
    * [x] From S3
    * [x] (using git-lfs or direct write if you are feeling smart ie. write to storage and write pointer file ...)

----

Migration steps

* Create a repo on `github.com/gift-data/{name-of-dataset}`
* Configure git repo with giftless as git-lfs server
* Copy over `datapackage.json` from s3 to repo
* Copy over files ... (using git-lfs or direct write if you are feeling smart ie. write to storage and write pointer file ...)

### Today

https://openspending.org/viewer/667df60aa07c34260eae9b55b2778712:presupuesto_de_uruguay?measure=%22MONTO_VIGENTE.sum%22&groups%5B%5D=%22AP_ID.AP_ID%22&filters%5BANO.ANO%5D%5B%5D=2019&order=%22MONTO_VIGENTE.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=es

* S3: http://s3.amazonaws.com/datastore.openspending.org/667df60aa07c34260eae9b55b2778712/presupuesto_de_uruguay/final/datapackage.json
  * Example resource: http://s3.amazonaws.com/datastore.openspending.org/667df60aa07c34260eae9b55b2778712/presupuesto_de_uruguay/final/data/presupuesto_de_uruguay.csv

### Future

github.com/gift-data/uruguay

```
datapackage.json
data/presupuesto_de_uruguay.csv # git-lfs stored using giftless to either s3 or gcs
```

Next

* Mini-portal (or publish on datahub)
  * `datahub.io/@gift-data/`
* A data API
* Data Publishing flow to create the `datapackage.json`

**Comment by sglavoie** [comment]
Upload succeeded! Generated log on the Git-LFS server (using uWSGI locally + Giftless cloned from source):
```
$ uwsgi -M -T --threads 2 -p 2 --manage-script-name \
    --module giftless.wsgi_entrypoint --callable app --http 127.0.0.1:8080
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Aug 31 13:26:45 2020] ***
compiled with version: 9.3.0 on 31 August 2020 18:16:44
os: Linux-5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
nodename: matebookd15
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/sglavoie/dev/datopian/github/giftless
detected binary path: /home/sglavoie/dev/datopian/github/giftless/.venv/bin/uwsgi
your processes number limit is 27328
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8080 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:41383 (port auto-assigned) fd 3
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
Python main interpreter initialized at 0x55d79ae25370
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
giftless.yaml
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55d79ae25370 pid: 49880 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 49880)
spawned uWSGI worker 1 (pid: 49883, cores: 2)
spawned uWSGI worker 2 (pid: 49884, cores: 2)
spawned uWSGI http 1 (pid: 49885)
[pid: 49884|app: 0|req: 1/1] 127.0.0.1 () {34 vars in 585 bytes} [Mon Aug 31 13:26:59 2020] POST /gift-data/presupuesto_de_uruguay/objects/batch => generated 13063 bytes
in 1940 msecs (HTTP/1.1 200) 2 headers in 86 bytes (1 switches on core 0)
[pid: 49884|app: 0|req: 3/2] 127.0.0.1 () {34 vars in 1069 bytes} [Mon Aug 31 13:27:01 2020] PUT /gift-data/presupuesto_de_uruguay/objects/storage/285ec6cb9db938654ca5a6b
2558ad4b7d94af8f9746ecaa5a94f34317ec20210 => generated 0 bytes in 2471 msecs (HTTP/1.1 200) 2 headers in 78 bytes (115 switches on core 1)
[pid: 49883|app: 0|req: 2/3] 127.0.0.1 () {34 vars in 1069 bytes} [Mon Aug 31 13:27:01 2020] PUT /gift-data/presupuesto_de_uruguay/objects/storage/0698e1a4ef0a0f1a7becc0c
96bb31a695504d67ccd627e4c24bcbb0513d8fd3a => generated 0 bytes in 3960 msecs (HTTP/1.1 200) 2 headers in 78 bytes (99 switches on core 1)
[pid: 49884|app: 0|req: 4/4] 127.0.0.1 () {34 vars in 1069 bytes} [Mon Aug 31 13:27:01 2020] PUT /gift-data/presupuesto_de_uruguay/objects/storage/184d6f26425718ccd1d382e
15ee537ac42706b1f78b0da198ab75030028420f8 => generated 0 bytes in 4057 msecs (HTTP/1.1 200) 2 headers in 78 bytes (138 switches on core 0)
[pid: 49884|app: 0|req: 5/5] 127.0.0.1 () {34 vars in 1069 bytes} [Mon Aug 31 13:27:04 2020] PUT /gift-data/presupuesto_de_uruguay/objects/storage/a0154a01406c60380e60664
71e987e3d73f49e55c16b71a15dce052eb4a95aaf => generated 0 bytes in 3652 msecs (HTTP/1.1 200) 2 headers in 78 bytes (103 switches on core 1)
[pid: 49884|app: 0|req: 6/6] 127.0.0.1 () {34 vars in 1069 bytes} [Mon Aug 31 13:27:05 2020] PUT /gift-data/presupuesto_de_uruguay/objects/storage/0f2f66eb2e1155579c5f43c
c2a647132977ae629649087f21c52f0eba5bfdf13 => generated 0 bytes in 3635 msecs (HTTP/1.1 200) 2 headers in 78 bytes (144 switches on core 0)
[pid: 49883|app: 0|req: 3/7] 127.0.0.1 () {34 vars in 1069 bytes} [Mon Aug 31 13:27:05 2020] PUT /gift-data/presupuesto_de_uruguay/objects/storage/c1bf2c2fdc500ded0ce2692
e324e46dea67d7dcff10facc753e9b1a70b179867 => generated 0 bytes in 3752 msecs (HTTP/1.1 200) 2 headers in 78 bytes (92 switches on core 1)
[pid: 49884|app: 0|req: 7/8] 127.0.0.1 () {36 vars in 997 bytes} [Mon Aug 31 13:27:09 2020] POST /gift-data/presupuesto_de_uruguay/objects/storage/verify => generated 0 b
ytes in 75 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 0)
[pid: 49883|app: 0|req: 4/9] 127.0.0.1 () {36 vars in 997 bytes} [Mon Aug 31 13:27:09 2020] POST /gift-data/presupuesto_de_uruguay/objects/storage/verify => generated 0 b
ytes in 67 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 1)
[pid: 49883|app: 0|req: 5/10] 127.0.0.1 () {36 vars in 997 bytes} [Mon Aug 31 13:27:09 2020] POST /gift-data/presupuesto_de_uruguay/objects/storage/verify => generated 0
bytes in 94 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 1)
[pid: 49884|app: 0|req: 8/11] 127.0.0.1 () {36 vars in 997 bytes} [Mon Aug 31 13:27:09 2020] POST /gift-data/presupuesto_de_uruguay/objects/storage/verify => generated 0
bytes in 140 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 0)
[pid: 49883|app: 0|req: 6/12] 127.0.0.1 () {36 vars in 997 bytes} [Mon Aug 31 13:27:09 2020] POST /gift-data/presupuesto_de_uruguay/objects/storage/verify => generated 0
bytes in 67 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 1)
[pid: 49884|app: 0|req: 9/13] 127.0.0.1 () {36 vars in 997 bytes} [Mon Aug 31 13:27:09 2020] POST /gift-data/presupuesto_de_uruguay/objects/storage/verify => generated 0
bytes in 217 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 0)
[pid: 49884|app: 0|req: 10/14] 127.0.0.1 () {34 vars in 1069 bytes} [Mon Aug 31 13:27:07 2020] PUT /gift-data/presupuesto_de_uruguay/objects/storage/2701766e384d9af7d4557
d83d04fdfd4262f2e1f52f298e52a6f678cf0136705 => generated 0 bytes in 3118 msecs (HTTP/1.1 200) 2 headers in 78 bytes (104 switches on core 1)
[pid: 49884|app: 0|req: 11/15] 127.0.0.1 () {36 vars in 997 bytes} [Mon Aug 31 13:27:11 2020] POST /gift-data/presupuesto_de_uruguay/objects/storage/verify => generated 0
 bytes in 76 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 1)
[pid: 49883|app: 0|req: 7/16] 127.0.0.1 () {34 vars in 1070 bytes} [Mon Aug 31 13:27:09 2020] PUT /gift-data/presupuesto_de_uruguay/objects/storage/a035cfa8322e7039d295fa
5ea6d684fca8745b01ee8258682c195fdec87d8db4 => generated 0 bytes in 2986 msecs (HTTP/1.1 200) 2 headers in 78 bytes (148 switches on core 1)
[pid: 49884|app: 0|req: 11/17] 127.0.0.1 () {34 vars in 1069 bytes} [Mon Aug 31 13:27:09 2020] PUT /gift-data/presupuesto_de_uruguay/objects/storage/0a2029a6efbc0d041ca44
7e2860bee0da2bbac39724432e87d21a060786eb713 => generated 0 bytes in 2809 msecs (HTTP/1.1 200) 2 headers in 78 bytes (117 switches on core 0)
[pid: 49883|app: 0|req: 8/18] 127.0.0.1 () {36 vars in 997 bytes} [Mon Aug 31 13:27:12 2020] POST /gift-data/presupuesto_de_uruguay/objects/storage/verify => generated 0
bytes in 67 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 1)
[pid: 49884|app: 0|req: 12/19] 127.0.0.1 () {36 vars in 997 bytes} [Mon Aug 31 13:27:12 2020] POST /gift-data/presupuesto_de_uruguay/objects/storage/verify => generated 0
 bytes in 78 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 1)
[pid: 49883|app: 0|req: 9/20] 127.0.0.1 () {34 vars in 1068 bytes} [Mon Aug 31 13:27:01 2020] PUT /gift-data/presupuesto_de_uruguay/objects/storage/09b07603acac3685b1a8e9
3fdfc2fdcf40e3b0d89543896650786247f1043fbf => generated 0 bytes in 15676 msecs (HTTP/1.1 200) 2 headers in 78 bytes (765 switches on core 0)
[pid: 49883|app: 0|req: 9/21] 127.0.0.1 () {36 vars in 997 bytes} [Mon Aug 31 13:27:17 2020] POST /gift-data/presupuesto_de_uruguay/objects/storage/verify => generated 0
bytes in 96 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 1)
```

On GCS:

![image](https://user-images.githubusercontent.com/32682903/91754096-78099a00-eb8e-11ea-8a41-9c1a8d03b9ab.png)

Server config file:
```
TRANSFER_ADAPTERS:
  basic:
    factory: giftless.transfer.basic_streaming:factory
    options:
      storage_class: giftless.storage.google_cloud:GoogleCloudStorage
      storage_options:
        project_name: gift-data
        bucket_name: gift-data
        account_key_file: credentials.json
AUTH_PROVIDERS:
  - giftless.auth.allow_anon:read_write
```

`credentials.json` with service account:

```
{
  "type": "service_account",
  "project_id": "XXXXXXXXXXXXXXXXX",
  "private_key_id": "XXXXXXXXXXXXXXXXX",
  "private_key": "-----BEGIN PRIVATE KEY-----\nXXXXXXXXXXXXXXXXX\n-----END PRIVATE KEY-----\n",
  "client_email": "XXXXXXXXXXXXXXXXX.iam.gserviceaccount.com",
  "client_id": "XXXXXXXXXXXXXXXXX",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/XXXXXXXXXXXX.iam.gserviceaccount.com"
}
```

**Comment by sglavoie** [comment]
**Update**:

* All the repos for GIFT were created programmatically: https://github.com/gift-data
* All the resources and `datapackage.json` files were retrieved locally, ready to be uploaded to Google Cloud Storage. Script used:

```
from pathlib import Path
import json
import os

import requests

# Map name of repo to datapackage.json URL
REPOS = {
    "costa-rica-presupuesto-egresos-2017": "http://datastore.openspending.org/2e6c7fb02a09883c5556f341e814d3bf/egresos_2017_cr/final/datapackage.json",
    "costa-rica-presupuesto-egresos-2018": "http://datastore.openspending.org/2e6c7fb02a09883c5556f341e814d3bf/egreso_2018_cr/final/datapackage.json",
    "costa-rica-presupuesto-egresos-2019": "http://datastore.openspending.org/2e6c7fb02a09883c5556f341e814d3bf/egresos_2019_cr/final/datapackage.json",
    "costa-rica-presupuesto-egresos-2020": "http://datastore.openspending.org/2e6c7fb02a09883c5556f341e814d3bf/e2020_cr_ene_feb/final/datapackage.json",
    "costa-rica-presupuesto-ingresos-2017": "http://datastore.openspending.org/2e6c7fb02a09883c5556f341e814d3bf/ingresos_2017_cr/final/datapackage.json",
    "costa-rica-presupuesto-ingresos-2018": "http://datastore.openspending.org/2e6c7fb02a09883c5556f341e814d3bf/ingresos_2018_cr/final/datapackage.json",
    "costa-rica-presupuesto-ingresos-2019": "http://datastore.openspending.org/2e6c7fb02a09883c5556f341e814d3bf/ingresos_2019_cr/final/datapackage.json",
    "costa-rica-presupuesto-ingresos-2020": "http://datastore.openspending.org/2e6c7fb02a09883c5556f341e814d3bf/ingreso2020ene_may/final/datapackage.json",
    "croatia-budget-spending": "http://s3.amazonaws.com/datastore.openspending.org/667df60aa07c34260eae9b55b2778712/croatia-budget-spending/final/datapackage.json",
    "paraguay-2017": "https://s3.amazonaws.com:443/datastore.openspending.org/d2e8215903dc37020268704e584dda11/pgn-2017/datapackage.json",
    "presupuesto-mexico-2008-2019": "http://s3.amazonaws.com/datastore.openspending.org/667df60aa07c34260eae9b55b2778712/presupuesto_mexico/final/datapackage.json",
    "republica-dominicana-gastos-economica-2014-2020": "http://datastore.openspending.org/d12b5fcc290ca2a801abdf9603d5969b/ingresoseconomica/final/datapackage.json",
    "south-africa-national-estimates-2015-2019": "http://datastore.openspending.org/b9d2af843f3a7ca223eea07fb608e62a/budgeted-and-actual-national-expenditure-of-south-africa-uploaded-2019-11-01t1258/final/datapackage.json",
    "south-africa-provincial-estimates-2018-2019": "http://datastore.openspending.org/b9d2af843f3a7ca223eea07fb608e62a/estimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes/final/datapackage.json",
}


def generate_repos_empty_list_resources(repos=REPOS) -> dict:
    """Get a dictionary with the name of the repos we are interested in,
    each one being set to an empty list."""
    repos_list_resources = {}
    for repo_name in repos.keys():
        repos_list_resources[repo_name] = []
    return repos_list_resources


def download_data_packages(repos=REPOS):
    """Download  the datapackage.json file for each repo."""
    for repo_name, package_url in repos.items():
        repo_dir = Path(repo_name)
        repo_file = repo_dir / "datapackage.json"
        r = requests.get(package_url)

        with open(repo_file, "w") as f:
            f.write(r.text)


def get_resources(repos=REPOS) -> dict:
    """Download all the resources for each repo."""
    repos_list_resources = generate_repos_empty_list_resources()
    for repo_name, repo_resources in repos_list_resources.items():
        repo_path = Path(repo_name)
        repo_file = repo_path / "datapackage.json"
        repo_package_url = repos[repo_name].rstrip("datapackage.json")

        with open(repo_file) as f:
            content = f.read()
        json_content = json.loads(content)
        for resource in json_content["resources"]:
            resource_path = resource["path"]
            resource_url = repo_package_url + resource_path
            resource_local_path = repo_path / resource_path
            print("Getting", resource_url)
            print("saving to...", resource_local_path)

            if "/data" in resource_url:
                try:
                    os.mkdir(repo_path / "data")
                except FileExistsError:
                    pass

            r = requests.get(resource_url)
            with open(resource_local_path, "w") as f:
                f.write(r.text)


if __name__ == "__main__":
    download_data_packages()
    get_resources()
```

**Comment by rufuspollock** [comment]
@sglavoie great job 👏 

Small details: can we add acceptance criteria and can you update the issue tasks with the result as per the guidelines in the playbook.

Also i suggest putting the script (and the script for booting uwsgi) in e.g. a gist somewhere for now and linking that clearly from relevant items in the issue description. (You could even put this script in the migration repo we created).

**Comment by sglavoie** [comment]
@rufuspollock: Done.

* Issue description updated.
* Migration process documented in the [audit repo](https://github.com/openspending/audit-for-migration-2020/tree/master/s3_to_google_cloud_storage).

**Limitations to consider**:

* There is way too much data to backup and very little that we actually want to keep based on our selection criteria, therefore **the name of the repositories were hand-picked** to make sure all the necessary data for GIFT was uploaded to Google Cloud Storage (there were only a handful of datasets for GIFT to consider [from this page](http://www.fiscaltransparency.net/ofdp/)).
  * The remaining datasets could be named based on the description found in `datapackage.json` (or simply just from the **Title** column in the audit spreadsheet) but we would still need to have a list manually created to keep only what's desirable (which is quick to do from the [existing audit spreadsheet](https://docs.google.com/spreadsheets/d/1Cno0jUkfl8ozf0qjaNhuCmJEmMaL2U65sNONqVTEEnM/edit#gid=402256245)).
* This was performed successfully using a **Giftless server running locally**. @cuducos told me to look into setting this up with the DX setup but I was clueless on how to proceed and would have wasted too much time figuring this out on my own.

**Comment by sglavoie** [comment]
**FIXED**: Closing as all tasks were done and the GIFT migration has been completed.

* If we want to consider other datasets or setting up Giftless on a remote server, we can open separate issues for those.
* Feel free to re-open if something more might be necessary to be done as part of the initial tasks.
