### ISSUE TITLE
[GIFT] List of user stories

### ISSUE THREAD

**Issue by sglavoie** [openspending/openspending#1489]
## Acceptance

* [x] The OpenSpending Trello board has been backed up and has been deleted.

## Tasks

* [x] Retrieve all user stories from the OpenSpending Trello board. – **DONE**: [See comment below](https://github.com/openspending/openspending/issues/1489#issuecomment-723223605).
* [x] Move user stories to internal Google Docs document. – **DONE** (private access).

**Comment by sglavoie** [comment]
## User stories

### UI

* As a {Data Publishing User}, I want to be able to edit a dataset I have published, so I can correct or enhance existing data.
* As a {Data Publishing User}, I want to be able to edit the model of data I have already imported, so I can fix bugs or make enhancements in the API built for my data.
* As a {Data Publishing User}, I want to be able to delete a dataset I have published, so I can remove unwanted data from OpenSpending.
* As a {Platform Administrator}, I want to be able to *Hide* any dataset already added as *Public*, so that I can maintain Public/Hidden status for other users.
* As a {Data Publishing User}, I want to be able to edit the data source of data I have already imported, so I can fix bugs or make enhancements in the API built for my data.
* As a {Data Publishing User}, I want to be able to import data in Excel, so I do not have to convert data formats in order to use the data packager.
* As a {Data Publishing User}, I want to know what my data needs to be able to be visualised on a map, so I can visualise it on a map :)
* As a {Data Publishing User}, I want to be able to import data in JSON, so I do not have to convert data formats in order to use the data packager.
* As a {Data Publishing User}, I want to be able to import data from a Google Spreadsheet, so I do not have to convert data formats in order to use the data packager.
* As a {Data Publishing User}, I want to be able to import data from Fiscal Data Package descriptor file, so I do not have to convert data formats in order to use the data packager.
* As a {Data Publishing User}, I want to be able to provide the {Platform Administrator} with additional GeoJSON sources in order to improve the map-based visualisations of my data.
* As a {Data Consuming User}, I want to be able to filter, sort and aggregate data by multiple dimensions and measures, so I can get more granular views on the data.
* As a {Data Consuming User}, I want to be able to download a CSV of the data that is used in any visualisation I am viewing, so I can use the data in other tools.
* As a {Data Consuming User}, I want all monetary measures displayed to have currency symbols, so I can understand the meaning of the amount.
* As a {Data Consuming User}, I want to be able to change the display of all monetary measures across a set of currencies, to help me understand localised amounts in non-localised figures (example: GBP -> EURO).
* As a {Data Consuming User}, I want to see textual descriptions that accompany embedded visualisations, so I can more easily understand what I am viewing.

### API

* As an {API User}, I want to be able to understand if a user is a *Publisher*, so I can offer functionality based on *Dataset Publisher* privileges.
* As an {API User}, I want to be able to understand if a user is an *Administrator*, so I can offer functionality based on *Platform Administration* privileges.
* As an {API User}, I want to be able to get bordering regions|cities when I query a region|city, so I can provider wider visual context for mapping visualisations.
* As an {API User}, I want to have a flexible API using HASC codes for countries, regions and cities, so I can visualise budget data on maps.
* As an {API User}, I want to be able to get a CSV output of any cube-based query, so I can use work with tools that read CSV.
* As an {API User}, I want to be able to get a set of monetary measures transferred to different currencies (eg: GBP to EURO), so I can use this in scenarios that might enable comparison by normalisation.
* As an {API User}, I want to be able to use metadata to get results from multiple datasets, so I can build user experiences based on more than one dataset more easily.
* As an {API User}, I want to be able to normalise measures by population, so I work with datasets in reference to their contextual constraints.
* As an {API User}, I want to be able to normalise measures by geographical area, so I work with datasets in reference to their contextual constraints.
* As an {API User}, I want to be able to normalise measures by GDP, so I work with datasets in reference to their contextual constraints.
* As an {API User}, I want to be able to normalise measures by GINI and related socioeconomic indexes, so I work with datasets in reference to their contextual constraints.
* As an {API User}, I want to be able to get a relative percentage of a measure to the total of the dataset it comes from, so I can build alternative displays of the data.

### ETL

* As a {Data Publishing User}, I want to have my dataset update automatically as the source file(s) changes, so that OpenSpending always shows current data.

### Done

* As a {Data Publishing User}, I want to be able to add a dataset in a *Hidden* state, so that I can work on a dataset before having it discoverable via OpenSpending user interfaces.
* As a {Data Publishing User}, I want to be able to *Hide* a dataset that I have already added as *Public*, so that I can fix my mistakes or have a dataset primarily for my own use.
* As a {Data Publishing User}, I want a view on all the datasets I have published, so I can perform management actions on my own datasets.

**Comment by sglavoie** [comment]
**FIXED**: Closing as all necessary actions have been taken.
