### ISSUE TITLE
Portal (Read Frontend)

### ISSUE THREAD

**Issue by rufuspollock** [openspending/openspending#1491]
We will be replacing the current "portal" part of OpenSpending (ie. read frontend) with CKAN next generation frontend system  - see https://tech.datopian.com/frontend/

## Tasks

* [ ] Plan
* [ ] Implement

### Implement

* [ ] MetaStore (in memory)
  * [ ] List of datasets in a file
  * [ ] On boot up we load all of those datapackage.json for those datasets
* [ ] Indexing in e.g. lunr.js
* [ ] Cards on front page
