### ISSUE TITLE
[overview] Data store v2 - flat-file based

### ISSUE THREAD

**Issue by trickvi** [openspending/openspending#669]
**This is more of an overview, key components with detail of actual changes**

* [x] Spec of data.openspending.org layout (below)
* [ ] #731 - Spec for OpenSpending data package (what additional info) (below)
* [x] #703 - uploading service for DataStore
* [ ] #670 (improved data loading process)
* [x] Deployment of data.openspending.org
* [ ] Cache all existing datasets into data.openspending.org

------

As discussed on the dev meeting in August we plan to adopt the approach put forward in [OpenSpending Enhancement Proposal No 2](https://github.com/openspending/osep/blob/gh-pages/02-data-storage-and-data-pipeline.md) and:

**Create a flat-file based data store for OpenSpending data in [data package format](http://data.okfn.org/standards/data-package)**

Ultimately this flat-file store will replace the relational (postgres) database as the primary data store (we will still, of course, load the data into the postgres database.

![OpenSpending new data pipeline](https://docs.google.com/a/okfn.org/drawings/d/1quRc7emv7fPrezqX9YWfqiAfyk_A7KPZ3N8gux2NSh4/pub?w=600&h=262)

## What is needed here

1. Outline for how this is set up
2. How it fits with load process (this is described in #670 and there actual changes need to OS will likely be separate issues)

### Setup

Data store will be at http://data.openspending.org/

This is an s3 bucket with a simple file browser interface via https://github.com/rgrp/s3-bucket-listing

File layout:

<pre>
/datasets/{dataset-name}/ # data directory
</pre>

For data package structure see #731

### Extras

* (?) merge archive.openspending.org/
* For historical reasons we may need to keep around `/worldbank/`
  
## Notes (from dev meeting)

This backend has to be a service that can run, and validate the data packages (which must be standardised). Take a look at [source code for data.okfn.org](https://github.com/okfn/data.okfn.org) and reuse as much as possible.

Regarding data package standard. When implementing this, please raise the issue of standardised data packages on the dev mailing list since it's a big issue.

Ultimately this should provide both an api for software and direct access for data wranglers (with the right permissions).
