### ISSUE TITLE
Viewer UI/X implementation

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#874]
# Description

# Tasks

* [x] Implement updated header.
* [x] Implement updated footer.
* [x] Implement default "Workspace" state which has a table preview of first X lines of raw data, and a widget via which to "add visualisation" 
  * [x] clicking pops up list of possible vis widgets
* [x] Implement the basic UI for the "Control Panel" (elements, initial query options etc).
* [x] Use refactored babbage ui components, replacing the current use of the monolith babbage ui app.
* [x] Label view components from babbage by type. This could possibly be part of the API exposed via the babbage.ui library. For us, type is important for the type of queries we expose. @akariv should advise what types we have, and how to group.
* [x] Query options in the control panel are not going to be *all* possible query options via Babbage at this stage. @akariv will guide on what options for each vis type. Please be in contact for clarification.
* [x] Implement all the small tools that come with each view component added to the Workspace
* [x] Implement the logic to remove views from the workspace
* [x] Implement the logic that, once a view is *in* the workspace, the other views that can be added are only of the same type (so, in the dropdown of view components, show all, but disable the ones of the different types)

# Resources

* [PSDs are here](https://drive.google.com/drive/folders/0B0he-qr0BknoR3hqNHBpYzBBdk0)
* Some HTML, CSS and icons in the [Style Guide](https://github.com/openspending/os-style-guide)

![viewer_02_charts_01](https://cloud.githubusercontent.com/assets/791678/13353416/ea59c55e-dc9c-11e5-8e04-7b9e8a7f9d87.jpg)

![viewer_03_charts_01](https://cloud.githubusercontent.com/assets/791678/13353417/ea8af566-dc9c-11e5-9d62-1b5a6b5ae107.jpg)

![viewer_03_default_01](https://cloud.githubusercontent.com/assets/791678/13353418/ea90b8a2-dc9c-11e5-9fa3-579a2345a771.jpg)

**Comment by pwalsh** [comment]
@akariv ( cc @kravets-levko )

As part of the move to this design, we talked about limiting the control options based on the current visualisation(s) in the workspace. Could you write a mini-spec for this so Levko can implement it.

**Comment by pwalsh** [comment]
@akariv please check the task descriptions above, let me know if we need to update, and please work on what @kravets-levko needs so it is all smooth :).

**Comment by akariv** [comment]
### Application State
We have a few different types of charts in OS viewer. Some are based on similar concepts and interaction, and some are different.
The viewer will keep a separate state for each of these chart classes. Selecting a specific chart will load the state for that chart class - so 
- when switching from one chart type to another in the same class, the data selection will remain the same.
- when selecting a chart from another class, we’ll load the state for that class.
- when returning to a chart from a previously visited class, we will return to the last state for that specific class

On init, the ‘Table’ chart is selected with no grouping.
### Chart Types
The current classes are:
- Drilldown: Treemap, Pie-Chart, Bubble-Tree
- Sortable-Series: Bar Chart, Table
- Time-Series: Line/Area Chart
- 2D-Table: Pivot-Table

### Drilldown
A drilldown chart is one that basically allows to traverse along a hierarchy. 

#### UI Appearance and Behaviour 
- Under ‘Measures’ a list of all measures is shown, from which the user chooses one measure to use.
  - If there’s only one measure, this section should not appear and the only measure is auto-selected
- Under ‘Hierarchies’ a list of all hierarchies is shown, from which the user chooses one hierarchy to follow.
- Under ‘Filters’ a list of all dimensions. When clicking on a dimension, it expands while disclosing all possible values for that dimension.
  - Filters should be grouped by containing hierarchy
  - The selected value is always the key attribute.
  - If the dimension has a label attribute, then show the label for each value instead.
  - Clicking on a specific value creates a ‘cut’ parameter in the API call
  - You can only select one value for each dimension.
  - Once a hierarchy is selected, its dimensions are removed from the list of filters.
Sorting controls are not enabled.

#### API Handling
- At first there are no internal filters and and ‘drilldown’ API parameter is set to the highest dimension in the selected hierarchy.
- Clicking on the chart performs a ‘drilldown’ action:
  - Add a cut for the active dimension in the hierarchy 
  - change the active dimension to the next dimension in the selected hierarchy.
- Backing up from the drilldown means:
  - Removing the last cut added
  - change the active dimension to the previous dimension in the selected hierarchy.
- User provided filters and the ‘drilldown cuts’ are combined together in the ‘cut’ API parameter.
- Data should always be sorted by the measure value, descending.

### Sortable-Series

#### UI Appearance and Behaviour 
- Under ‘Measures’ a list of all measures is shown, from which the user chooses one measure to use.
  - If there’s only one measure, this section should not appear and the only measure is auto-selected
- Under ‘X-axis’ a list of all dimensions is shown, grouped by hierarchy
  - Only one dimension can be selected for the x-axis
  - The first dimension (top of the list in the UI) should be selected initially
- Under ‘Series’ a list of all dimensions is shown, grouped by hierarchy
  - Only one series can be selected - but it’s also possible not to have a series selected at all
  - Selecting a series makes the graph to appear as a multi-series graph. In this case a legend of sorts should be shown in the chart.
- Under ‘Filters’ a list of all dimensions is shown. Same as in ‘Drilldown’
- Data can be ordered according the measure or by the x-axis dimension, ascending or descending
  - Initially the ordering should be measure, descending
  - Clicking an active sort control toggles the direction (asc/desc)
  - Clicking an inactive sort control makes it active and disables all other sort controls.

#### API Handling
- ‘drilldown’ API parameter is derived from the x-axis selection and also the series selection in case it is made.
- The ‘cut’ API parameter is derived from the filter selection in a straightforward manner.
- The ordering of the data is derived from the sort controls state

### Time-Series

#### UI Appearance and Behaviour 

- This class is only enabled if there’s a ‘time’ typed dimension
- Under ‘Measures’ a list of all measures is shown, from which the user chooses one measure to use.
  - If there’s only one measure, this section should not appear and the only measure is auto-selected
- Under ‘Series’ a list of all dimensions is shown, grouped by hierarchy
  - Only one series can be selected - but it’s also possible not to have a series selected at all
  - Selecting a series makes the graph to appear as a multi-series graph. In this case a legend of sorts should be shown in the chart.
- Under ‘Filters’ a list of all dimensions is shown. Same as in ‘Drilldown’
- Sorting controls are not enabled.

#### API Handling

- ‘drilldown’ API parameter should always contain the time dimension.
- In case a series dimension was selected, it should be appended to the ‘drilldown’ API parameter
- The ‘cut’ API parameter is derived from the filter selection in a straightforward manner.
- Data is always sorted by the time dimension.

### 2D-Table

#### UI Appearance and Behaviour

- Under ‘Measures’ a list of all measures is shown, from which the user chooses one measure to use.
  - If there’s only one measure, this section should not appear and the only measure is auto-selected
- Under ‘Rows’ and ‘Columns’ a list of all dimensions is shown, grouped by hierarchy
  - More than one dimension can be selected for in each section (but at least one)
- Under ‘Filters’ a list of all dimensions is shown. Same as in ‘Drilldown’
- Sorting controls are not enabled (if needed, sorting should be done internally in the chart)
	
#### API Handling

- ‘drilldown’ API parameter should contain a unique set of all dimensions selected in Rows and Columns.
- The ‘cut’ API parameter is derived from the filter selection in a straightforward manner.
- Data sorting is undefined

**Comment by akariv** [comment]
@kravets-levko 
Also @smth I added a 'sorting control' above, which we'll need to incorporate into the design

**Comment by akariv** [comment]
For the filter sections, let's treat differently cases when there are more than N options, something along the lines of this:
- If there are less than N values, then just show the different values as now
- If there are more, put a search box instead to filter the values shown. Never show more than N values. If filter returns more than N values, show a '...' after the last value
- Selected values are pushed above the search box, when removed they're also removed from there.

**Comment by pwalsh** [comment]
@kravets-levko the whole thing with "view types" ( @akariv calls it "chart types" here https://github.com/openspending/openspending/issues/874#issuecomment-199210122 ) should be added into babbage.ui as part of its public API, to keep the info centralised. ok?

**Comment by kravets-levko** [comment]
@akariv I decided to make own types for line charts (Time Series) and geoview (Location type). Generally Location is the same as Time Series, but for Time Series I show only dimensions with `datetime` type, and for Location only `location` dimensions - I think it makes sense.

**Comment by akariv** [comment]
Good call @kravets-levko.
We also need to make sure that it's possible to add a Table chart to either map, time-series or sortable-series kind of charts.

**Comment by pwalsh** [comment]
@akariv are we done here?

**Comment by akariv** [comment]
I'll do a proper functionality review tomorrow before I close this.

**Comment by akariv** [comment]
In drilldown mode (e.g. treemap), I get this:
![screen shot 2016-03-31 at 11 28 33 am](https://cloud.githubusercontent.com/assets/265333/14170093/544d72c4-f734-11e5-8766-d123709f09bf.png)

There should be 3 top level sections: `Measures`, `Hierarchies` and `Filters`. The dimension list inside the `Filters` section should be separated by hierarchy (as it is now).

**Comment by akariv** [comment]
Similarly for the Pivot table, I get this:
![screen shot 2016-03-31 at 11 57 17 am](https://cloud.githubusercontent.com/assets/265333/14170720/d0101f6c-f737-11e5-9e35-bf91395587e3.png)

There should be 4 top level sections: `Measures`, `Rows`, Columns` and `Filters`. Inside rows & columns a list of dimensions, grouped by hierarchy (expanding menu per hierarchy is not a must if it complicates things). Filters as above.

The general rule here is that similar things should have the same style - so 'Measures' is on the same level as 'Rows', but have very different styles.

**Comment by akariv** [comment]
Same goes for bar chart (no screenshot needed I think).
One other point is that the filter section should look the same in all views - e.g. some have the hierarchy titles and some don't.

**Comment by kravets-levko** [comment]
Hi @akariv! Thanks for feedback. Currently I have no idea how to do things better within current UI design - it is not intended to create multi-level menus. If you have some ideas - I'll be really happy to know them.

**Comment by akariv** [comment]
ok @kravets-levko, here's what I suggest for now (and we'll let @smth fix the design in a later stage) 
- first of all, top level section titles will be from the grey-small-font style
- this means that the measure section should be a list of items and not expandable
- same goes for the 'hierarchies' section
- the filters section has one section title ('Filters'). The rest looks similar to now, but no hierarchy names - just separator bars.

Another issue I'm encountering is that refreshing the window does not restore the visualisations in the page.

**Comment by akariv** [comment]
I opened #911, #912 and #913 to continue work on needed fixes, and I'm closing this issue.
