### ISSUE TITLE
Embed routes for each data view

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#885]
# Description

The Viewer allows a user to see data via particular views (visualisations). The whole viewer itself is embeddable. We also want each individual view (all the views we supply via babbage.ui) to be embeddable too. When that is possible, each view in the new Viewer Workspace (https://github.com/openspending/openspending/issues/874) could potentially have an embed URL to embed a particular state.

# Tasks

* [x] Create a new embed endpoint, for particular views. These endpoints should support **all** the params that the Viewer endpoint supports for embedding. The URL structure should be like: `/embed/{viewName}/?{params}`
  * [x] in order to support views as they get added to babbage.ui, you should be able to dynamically read the view names from babbage.ui for the `viewName` URL param. Example: `/embed/treemap/?{params}`
  * [x] Unknown view names should 404. Example: `/embed/mountainview/?{params}`
  * [x] `viewName` should be all lower case :)
* [x] Simple functional tests for the endpoints

**Comment by pwalsh** [comment]
@akariv does this look ok. Have I missed anything?

**Comment by akariv** [comment]
@pwalsh yes, looks ok to me

**Comment by borysyuk** [comment]
@pwalsh there is missed package name in your url structure.
So, I think, url should be like this: /embed/treemap/00_01_uganda?some-params

**Comment by pwalsh** [comment]
@borysyuk yes, correct, thanks.

**Comment by pwalsh** [comment]
@akariv can we close this now? I think yes, but want to check with you.
