### ISSUE TITLE
Explorer UI/X

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#892]
# Description

The OS Explorer provides a way to discover datasets in the OpenSpending Database. The first version will be a very simple way to explorer data, powered by a search API.

# Tasks

* [ ] Home page / entry point
* [ ] Result page for a query
* [ ] Advanced search to target certain dimensions, such as location (get me all datasets from Europe, or, Germny) and datetime, (get me all datasets from 2009)
* [ ] Navigate to Viewer - once the user actually selects a dataset to dive into, she is directed to the viewer for that dataset

## Screenshots based on CKAN prototype of registry

<img width="1280" alt="screenshot 2016-03-17 10 59 03" src="https://cloud.githubusercontent.com/assets/791678/13841528/1e160886-ec32-11e5-9cd8-d096b104feb6.png">
<img width="1280" alt="screenshot 2016-03-17 10 59 16" src="https://cloud.githubusercontent.com/assets/791678/13841529/1e547314-ec32-11e5-9a21-5b5c7ef29410.png">
<img width="1280" alt="screenshot 2016-03-17 10 59 56" src="https://cloud.githubusercontent.com/assets/791678/13841530/1e5a0540-ec32-11e5-9b62-0240446b70ff.png">
<img width="1280" alt="screenshot 2016-03-17 11 00 03" src="https://cloud.githubusercontent.com/assets/791678/13841531/1e5ac778-ec32-11e5-85f2-c52b1797c26a.png">

**Comment by smth** [comment]
Applying the new styling to the content in those screenshots gets us this:

![explorer_01_home_01](https://cloud.githubusercontent.com/assets/1375708/14780479/f69fbf74-0ad4-11e6-81e1-c93f187b1a0d.jpg)
![explorer_01_results_01](https://cloud.githubusercontent.com/assets/1375708/14780484/fa5b2aa4-0ad4-11e6-858f-dbd146554095.jpg)

Do we need anything further?

**Comment by akariv** [comment]
Looks great @smth !

@kravets-levko let's use the first mock as the home page, and the second one for the 'advanced search' (which you can get to using a link below the search box)
